name: Release doc

on:
  push:
    tags:
    - 'v*'
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: ${{ github.ref }}
          body_path: ${{steps.github_release.outputs.changelog}}
          token: ${{ secrets.PAT }}
