name: Release doc

on:
  push:
    tags:
    - 'v*'
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: ${{ github.ref }}
          body_path: ${{steps.github_release.outputs.changelog}}
          token: ${{ secrets.PAT }}
